create table usersjson(
id serial primary key,
info json not null
)

SELECT *FROM usersjson

INSERT INTO usersjson (info)
VALUES (' { "firstname" : "Shweta",  "lastname" : "Bangar" } ')

INSERT INTO usersjson (info)
VALUES (' { "firstname" : "Shweta",  "lastname" : "Bangar" } '),
		(' { "firstname" : "Sachin",  "lastname" : "Bangar" } '),
		(' { "firstname" : "Siddhi",  "lastname" : "Bangar" } '),
		(' { "firstname" : "Sujal",  "lastname" : "Bangar" } ')
		
INSERT INTO usersjson (info)
VALUES (' { "firstname" : "Rheea",  "lastname" : "Bangar", "role" : "Manager" } ');

SELECT info->'firstname' AS Firstname FROM usersjson;

INSERT INTO usersjson (info)
VALUES ( ' { "firstname" : "Krishna", "lastname" : "Shinde" , "contacts" : {
		"mobileno" : {"1234567890"},
		"address" : {"Andheri"}
		}}' );

--we are using string (->) + text(->>)
insert into usersjson (info)
values('{ "firstName" : "Amit" , "lastName" : "Patil", "contacts" :{ "mobileNo":"9876543210","address": "Andheri" } }');

SELECT info-> 'contacts' ->> 'mobileno' from usersjson

select info->'contacts'->>'mobileNo' from usersjson
where info->'contacts'->>'mobileNo' is not null;


CREATE TABLE orders (
id serial NOT NULL PRIMARY KEY,
info json NOT NULL
);
INSERT INTO orders (info)
VALUES('{ "customer": "John Doe", "items": {"product": "Beer","qty": 6}}');
INSERT INTO orders (info)
VALUES('{ "customer": "Lily Bush", "items": {"product": "Diaper","qty": 24}}'),
('{ "customer": "Josh William", "items": {"product": "Toy Car","qty": 1}}'),
('{ "customer": "Mary Clark", "items": {"product": "Toy Train","qty": 2}}');

select * from orders;

select min(CAST(info->'items'->>'qty' as INTEGER)),
max(CAST(info->'items'->>'qty' as INTEGER)),
sum(CAST(info->'items'->>'qty' as INTEGER)),
avg(CAST(info->'items'->>'qty' as INTEGER))
from orders;

SELECT json_each (info)
FROM orders;

SELECT json_object_keys (info->'items')
FROM orders;

SELECT json_typeof (info->'items')
FROM orders;


--*adding array to json info"                                                                insert into usersjson (info)
insert into usersjson (info) values('{ "firstName" : "Shweta" , "lastName" : "Patil", "contacts" :{ "mobileNo":["9876543210","9876543220"],"address": "Andheri" } }');select info->'contacts'->>'mobileNo' from usersjson;
select info->'contacts'->>'mobileNo' FROM usersjson




-- PartII - PostgreSQL Array
CREATE TABLE contacts (
id serial PRIMARY KEY,
name VARCHAR (100),
phones TEXT []
);
INSERT INTO contacts (name, phones)
VALUES ('John Doe' ,ARRAY [ '(408)-589-5846','(408)-589-5555' ]),
('John ' ,ARRAY [ '(408)-589-5847','(408)-589-5554' ]),
('Doe' ,ARRAY [ '(408)-589-5848','(408)-589-5553' ]),
('Mark' ,ARRAY [ '(408)-589-5849','(408)-589-5552' ]),
('Steve' ,ARRAY [ '(408)-589-5850','(408)-589-5551' ]);

select id,name,phones from contacts;
select id,name,phones[1] from contacts;
select id,name,phones[2] from contacts;

--Server managed transaction
DROP TABLE IF EXISTS accounts;

CREATE TABLE account (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO account(name,balance)
VALUES('Bob',10000);

INSERT INTO account(name,balance)
VALUES('Bob BUILDER',10000);

BEGIN TRANSACTION;
INSERT INTO account(name,balance)
VALUES('Alice',10000);


select * from account;
commit;


